spring:
  application:
    name: Crowdsourced-Waste-Collection-Recycling-System
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Waste;encrypt=true;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:72d6236b1a543277ad6973b2693a14ab13c437f8749b185a301f5034bbe3de36}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

open:
  api:
    title: "Crowdsourced Waste Collection & Recycling System API"
    version: "1.0.0"
    description: "Tài liệu API cho hệ thống thu gom và tái chế rác thải dựa trên cộng đồng."

